[project]
requires-python = ">=3.10"
dynamic = ["version", "dependencies", "optional-dependencies"]
name = "ctlssa"
readme = "README.md"

[tool.setuptools.dynamic]
version = {attr = "1"}
dependencies = {file = ["requirements.txt"]}
optional-dependencies = {dev = {file = ["requirements-dev.txt"]},deploy = {file = ["requirements-deploy.txt"]}}


[tool.pytest.ini_options]
minversion = "6.0"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
# testpaths = ["tests"]
norecursedirs = ["*fixtures*", "*locale*", "*migrations*", "*static*", "*uploads*", "resources", "*templates*", "*.devenv*", "*.pytest_cache*", "*htmlcov*", "*tools*", "*vendor*"]
DJANGO_SETTINGS_MODULE = "app.settings"

[tool.black]
line-length = 120
exclude = "vendor/|docs/|\\..+/"

[tool.coverage.run]
# include = ["*"]
omit = ["vendor/*","*migrations*","docs/*"]
branch = true

[tool.coverage.report]
skip_covered = true
show_missing = true

[tool.isort]
line_length = 120
known_first_party = "suggestions"

[tool.pep8]
max-line-length = 120

[tool.pylama]
# temporary ignore these errors/warnings since pylama update (10-04-2018)
# until autopep8 is able to fix these automatically
# https://github.com/hhatto/autopep8/commit/eeb0ec07c274db82a19fc2f95f5053407f2ad47d
# https://github.com/hhatto/autopep8/issues/372
# E203 black does [1 : 2] and pylama wants: [1:2]
ignore = "E252,W605,E203"
skip = "*/migrations/*,vendor/*,docs/*,build/*,.*/*"
linters = "pycodestyle,pyflakes"

[tool.pylama.linter.pycodestyle]
max_line_length = 120

[tool.pylint.format]
# unused-argument disabled because of kwargs called consistently from the scanning framework
# fixme diabled because it's dumb to remove documentation and decisions over not having them in a backlog
disable="missing-module-docstring,missing-class-docstring,missing-function-docstring,fixme,pointless-string-statement,no-name-in-module,duplicate-code,wrong-import-order,unused-argument"
max-line-length = 120
extension-pkg-whitelist = "pydantic"
ignore = "tests"
reports = true
output-format = "colorized"
jobs = 0
load-plugins = "pylint_django"
django-settings-module = "app.settings"

[tool.bandit]
targets = "suggestions"

[tool.autoflake]
recursive = true
in-place = true
remove-all-unused-imports = true
exclude = "*/migrations/*,./vendor/*,./docs/*,./build/*"
